version: '3.8'
services:
  postgres:
    container_name: postgres
    image: 'postgres:15'
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./backend/.env
    volumes:
      - './pgsql:/var/lib/postgresql/data'
    networks:
      - default
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:80"
    links:
      - postgres
    volumes:
      - './backend/media:/app/media'
      - './backend/static:/app/static'
    depends_on:
      - postgres
    networks:
      - default
  
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './backend/static:/app/static'
      - './backend/media:/app/media'
    networks:
      - default
    links:
      - backend
    depends_on:
      - backend

networks:
  default:
    driver: bridge

volumes:
  pgsql:
    driver: local