# Generated by Django 4.2.6 on 2023-10-21 20:27

import base_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisttoken',
            name='expire',
            field=models.DateTimeField(default=base_auth.models.default_expire_time, verbose_name='expire'),
        ),
    ]
